### PR TITLE
Added URL handling and a version folder

### PR DESCRIPTION
**Pull request by richarddubay**
This PR:
* Updates the OneSignal plugin to handle the new ability in Rock to pass an action URL to push notifications.
* Adds a "Versions" folder where we can copy the current version of the DLL to before we make changes that only work once you've reached a certain version of Rock. This is for backwards compatibility with Rock versions.

### CODE REVIEW

**Comment by richarddubay** [comment]
@conrad-vanl @vinnyjth Added y'all here even though I know y'all probably can't test this. Just wanted to get your eyes on this. And at least make sure that the simple versioning idea makes sense before I merge this.

**Comment by richarddubay** [comment]
@conrad-vanl @vinnyjth Any thoughts here? Mainly ... are we okay with versioning just by copying the last versions DLL into a folder?

**Comment by vinnyjth** [comment]
@richarddubay I'm fine with this! Would it be possible to generate versions of the plugin for older versions of Rock? I would be happy to do the leg work if you push me in the right direction :)

**Comment by richarddubay** [comment]
@vinnyjth Yeah, technically that's possible. Specifically for version 10, you'd have to undo a few commits (namely, go back to before this PR: https://github.com/ApollosProject/apollos-onesignal/pull/3) and rebuild the project. Then put that DLL in a folder. You wouldn't even have to save your work other than that DLL. Does that make sense?

**Pull request merged**
